  streak: 7,
  stats: {
    totalStudyTime: 750,
    missionsCompleted: 45,
    vocabularyLearned: 230,
    pronunciationAccuracy: 85,
  },
  inventory: {
    hints: 3,
    timeExtensions: 2,
    heartRefills: 1,
  },
};

export const vocabularyCategories: VocabularyCategory[] = [
  {
    id: "food",
    name: "음식",
    emoji: "🍎",
    wordsLearned: 10,
    totalWords: 10,
  },
  {
    id: "animals",
    name: "동물",
    emoji: "🐶",
    wordsLearned: 7,
    totalWords: 10,
  },
  {
    id: "colors",
    name: "색깔",
    emoji: "🎨",
    wordsLearned: 0,
    totalWords: 10,
  },
  {
    id: "numbers",
    name: "숫자",
    emoji: "🔢",
    wordsLearned: 10,
    totalWords: 10,
  },
  {
    id: "family",
    name: "가족",
    emoji: "👨‍👩‍👧‍👦",
    wordsLearned: 5,
    totalWords: 10,
  },
  {
    id: "body",
    name: "신체",
    emoji: "👁️",
    wordsLearned: 8,
    totalWords: 10,
  },
  {
    id: "weather",
    name: "날씨",
    emoji: "☀️",
    wordsLearned: 3,
    totalWords: 10,
  },
  {
    id: "clothes",
    name: "옷",
    emoji: "👕",
    wordsLearned: 0,
    totalWords: 10,
  },
  {
    id: "school",
    name: "학교",
    emoji: "🏫",
    wordsLearned: 6,
    totalWords: 10,
  },
  {
    id: "toys",
    name: "장난감",
    emoji: "🧸",
    wordsLearned: 4,
    totalWords: 10,
  },
  {
    id: "transportation",
    name: "교통",
    emoji: "🚗",
    wordsLearned: 2,
    totalWords: 10,
  },
  {
    id: "nature",
    name: "자연",
    emoji: "🌳",
    wordsLearned: 0,
    totalWords: 10,
  },
  {