"""add_child_pin_avatar

Revision ID: 707faa12c1fd
Revises: af23b9b43316
Create Date: 2026-02-14 11:05:00.808680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707faa12c1fd'
down_revision: Union[str, None] = 'af23b9b43316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('children', sa.Column('avatar_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'avatar_id')
    op.drop_column('children', 'pin_hash')
    # ### end Alembic commands ###
