"""initial_schema_py311

Revision ID: af23b9b43316
Revises: 
Create Date: 2026-02-14 10:54:57.443689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af23b9b43316'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('curriculum_unit_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('target_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('instructions_for_ai', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('intro_narrator_script', sa.Text(), nullable=True),
    sa.Column('transition_trigger', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('curriculum_units',
    sa.Column('curriculum_unit_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('target_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('language_mode', sa.String(length=20), nullable=False),
    sa.Column('clumsiness_level', sa.Integer(), nullable=False),
    sa.Column('korean_ratio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('curriculum_unit_id')
    )
    op.create_table('family_accounts',
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_index(op.f('ix_family_accounts_contact_email'), 'family_accounts', ['contact_email'], unique=True)
    op.create_table('skills',
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('age_band', sa.String(length=10), nullable=True),
    sa.Column('can_do_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_schema_version', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('subscription_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowed_sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('task_definitions',
    sa.Column('task_definition_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('expected_response_pattern', sa.Text(), nullable=True),
    sa.Column('target_skill_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('task_definition_id')
    )
    op.create_table('children',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('primary_language', sa.String(length=10), nullable=False),
    sa.Column('secondary_language', sa.String(length=10), nullable=True),
    sa.Column('development_stage_language', sa.String(length=50), nullable=True),
    sa.Column('preferences_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_accounts.family_id'], ),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_accounts.family_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('period_start_date', sa.DateTime(), nullable=False),
    sa.Column('period_end_date', sa.DateTime(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('strengths_summary', sa.Text(), nullable=True),
    sa.Column('areas_to_improve', sa.Text(), nullable=True),
    sa.Column('recommendations_next_month', sa.Text(), nullable=True),
    sa.Column('delivery_channel', sa.String(length=30), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['family_accounts.family_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('language_mode', sa.String(length=20), nullable=False),
    sa.Column('curriculum_unit_id', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('emotional_state_overall', sa.String(length=30), nullable=True),
    sa.Column('raw_audio_path', sa.Text(), nullable=True),
    sa.Column('stt_processed', sa.Boolean(), nullable=False),
    sa.Column('flag_for_expert_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('skill_levels',
    sa.Column('skill_level_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('percentile_by_age', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('evaluation_method', sa.String(length=30), nullable=False),
    sa.Column('evaluation_model_version', sa.String(length=10), nullable=False),
    sa.Column('skill_schema_version', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('skill_level_id')
    )
    op.create_table('report_skill_summaries',
    sa.Column('report_skill_summary_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('summary_for_parent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('report_skill_summary_id')
    )
    op.create_table('session_activities',
    sa.Column('session_activity_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_activity_id')
    )
    op.create_table('task_attempts',
    sa.Column('task_attempt_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('task_definition_id', sa.UUID(), nullable=True),
    sa.Column('expected_response_pattern', sa.Text(), nullable=True),
    sa.Column('evaluated_correctness', sa.String(length=30), nullable=True),
    sa.Column('related_utterance_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('instruction_understood', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('task_attempt_id')
    )
    op.create_table('utterances',
    sa.Column('utterance_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_activity_id', sa.UUID(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker_type', sa.String(length=10), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=True),
    sa.Column('text_normalized', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('dominant_language', sa.String(length=10), nullable=True),
    sa.Column('language_mix_ratio_ko', sa.Float(), nullable=True),
    sa.Column('language_mix_ratio_en', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('unique_word_count', sa.Integer(), nullable=True),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('emotion_label', sa.String(length=30), nullable=True),
    sa.Column('utterance_role', sa.String(length=30), nullable=True),
    sa.Column('expected_child_response_type', sa.String(length=30), nullable=True),
    sa.Column('stt_engine', sa.String(length=50), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('utterance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utterances')
    op.drop_table('task_attempts')
    op.drop_table('session_activities')
    op.drop_table('report_skill_summaries')
    op.drop_table('skill_levels')
    op.drop_table('sessions')
    op.drop_table('reports')
    op.drop_table('subscriptions')
    op.drop_table('children')
    op.drop_table('task_definitions')
    op.drop_table('subscription_plans')
    op.drop_table('skills')
    op.drop_index(op.f('ix_family_accounts_contact_email'), table_name='family_accounts')
    op.drop_table('family_accounts')
    op.drop_table('curriculum_units')
    op.drop_table('activities')
    # ### end Alembic commands ###
